application: team-pulse 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /googledc1aa51b85426f7d\.html
  static_files: static/googledc1aa51b85426f7d.html
  upload: static/googledc1aa51b85426f7d.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: pulsehandler.app
 
libraries:
- name: jinja2
  version: latest

error_handlers:
- file: /templates/default_error.html
